version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      -  $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Building the Docker image...
      - docker build   -t $IMAGE_REPO_NAME:$(cat ./VERSION)  --build-arg IMAGE_REPO_NAME:${IMAGE_REPO_NAME}  --build-arg  AWS_ACCOUNT_ID:${AWS_ACCOUNT_ID}  .
      - docker tag $IMAGE_REPO_NAME:$(cat ./VERSION) $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$(cat ./VERSION)
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$(cat ./VERSION)