version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      -  echo Logging in to Amazon ECR...
      -  $(aws ecr get-login --no-include-email --region us-east-1)
      -  git clone https://github.com/idasilva/npe-config.git
      -  pwd
      -  ls
      -  cd internal
      -  pwd
      -  ls
      -  cd nep-config
      -  pwd
      -  ls
      -  mv ./nep-config/config ./config &&  cd .. && rm -rf ../nep-config
  build:
    commands:
      - echo Building the Docker image...
      - docker build   -t $IMAGE_REPO_NAME:$(cat ./VERSION)  .
      - docker tag $IMAGE_REPO_NAME:$(cat ./VERSION) $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$(cat ./VERSION)
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$(cat ./VERSION)