version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      -  echo Logging in to Amazon ECR...
      -  $(aws ecr get-login --no-include-email --region us-east-1)
      -  aws codecommit get-file --repository-name config --commit-specifier main  --file-path config.yaml --query fileContent --output text | base64 -d
  build:
    commands:
      - echo Building the Docker image...
      - docker build   -t $IMAGE_REPO_NAME:$(cat ./VERSION)  .
      - docker tag $IMAGE_REPO_NAME:$(cat ./VERSION) $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$(cat ./VERSION)
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/$IMAGE_REPO_NAME:$(cat ./VERSION)